Updating dimipiraat couch profile
hackercouch/hackercouch pull request #285
Opened 2023-10-03 17:29 UTC by dhuyvetter

Updating couch ninfo as I have moved places. Also updating social links. Doing this from another Github account as I have lost the password for @dimipiraat

2023-10-04 06:23 UTC, ppaeps requested changes

2023-10-04 06:23 UTC, ppaeps commented on _couches/dimipiraat.md
>  github: dimipiraat
If you've lost control of the @dimipiraat account, perhaps you should also update the `github:` tag in the couch file. :)

2023-10-04 06:23 UTC, ppaeps commented on _couches/dimipiraat.md
>  github: dimipiraat
(Why does GitHub assign this review comment to the wrong line?  I'm sure the requested change is obvious though.)

2023-10-25 17:09 UTC, dimipiraat commented
I have access to my Github account again so I'll make a pull request from this account instead.

2025-08-17 17:27 UTC, closed without merging